name: "aarch64-multiplatform "
on:
  schedule:
    - cron: '12 4 * * *'
  workflow_dispatch:
jobs:
  build-releases:
    strategy:
      matrix:
        releases: [release-24.05,release-24.11]
    uses: ./.github/workflows/build-multiple.yml
    with:
      nixpkgs: ${{ matrix.releases }}
      architecture: aarch64-multiplatform
      cache: "true"
