name: "armv7-hf-multiplatform "
on:
  schedule:
    - cron: '12 6 * * *'
  workflow_dispatch:
jobs:
  build-releases:
    uses: ./.github/workflows/build-multiple.yml
    with:
      branch: release-23.11
      architecture: armv7l-hf-multiplatform
      build_legacy: false
