name: Releases (22.05, 22.11, 23.05, 23.11)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '12 6 * * *'
  workflow_dispatch:

jobs:
  build-releases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [22.05, 22.11, 23.05, 23.11]
    steps:
      - uses: ./.github/workflows/build-multiple.yml
        with: 
              branch: release-${{ matrix.version }}