name: Format check
on:
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
        default: "notalltim/nix-proto"
      branch:
        type: string
        required: false
        default: "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ inputs.repo == 'notalltim/nix-proto'}}
        with:
          sparse-checkout: .github
          path: action
          ref: refs/heads/${{ inputs.branch }}
      - uses: actions/checkout@v4
        if: ${{ inputs.repo != 'notalltim/nix-proto'}}
        with:
          sparse-checkout: .github
          path: action
          ref: refs/heads/main
      - name: Format
        uses: ./action/.github/actions/format
