name: "PR Validation"
on:
  pull_request:
    branches:
      - main
jobs:
  build-supported-cross:
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        releases: [release-24.11, release-25.05]
        architectures: [armv7l-hf-multiplatform, aarch64-multiplatform]
    uses: ./.github/workflows/build-multiple.yml
    with:
      nixpkgs: ${{ matrix.releases }}
      architecture: ${{ matrix.architectures }}
      repo: ${{ github.event.pull_request.head.repo.full_name }}
      branch: ${{ github.event.pull_request.head.ref }}
      cache: "true"
  build-supported-releases:
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        releases: [release-23.11, release-24.05, release-24.11, release-25.05, nixpkgs-unstable, master]
    uses: ./.github/workflows/build-multiple.yml
    with:
      nixpkgs: ${{ matrix.releases }}
      repo: ${{ github.event.pull_request.head.repo.full_name }}
      branch: ${{ github.event.pull_request.head.ref }}
  check-format:
    uses: ./.github/workflows/format.yml
    with:
      repo: ${{ github.event.pull_request.head.repo.full_name }}
      branch: ${{ github.event.pull_request.head.ref }}
  it-all-good:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build-supported-releases
      - build-supported-cross
      - check-format
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
