name: "PR Validation"
on:
  pull_request:
    branches:
      - main
jobs:
  build-supported-releases:
    strategy:
      matrix:
        branches: [release-22.05, release-22.11, release-23.05, release-23.11, nixpkgs-unstable, master]
    uses: ./.github/workflows/build-multiple.yml
    with:
        branch: ${{ matrix.branches }}
  it-all-good:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build-supported-releases
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
