name: "24.11 "
on:
  schedule:
    - cron: '12 6 * * *'
  workflow_dispatch:
jobs:
  build-releases:
    uses: ./.github/workflows/build-multiple.yml
    with:
      nixpkgs: release-24.11
      cache: "true"
