name: "22.05 "
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-releases:
    uses: ./.github/workflows/build-multiple.yml
    with:
        branch: release-22.05