name: Unstable
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '12 6 * * *'
  workflow_dispatch:

jobs:
  build-unstable:
    strategy:
      matrix:
        branches: [master, nixpkgs-unstable]
    uses: ./.github/workflows/build-multiple.yml
    with:
      branch: ${{ matrix.branches }}