name: unstable
on:
  schedule:
    - cron: '12 6 * * *'
  workflow_dispatch:
jobs:
  build-releases:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/build-multiple.yml
    with:
      nixpkgs: nixpkgs-unstable
      cache: "true"
