name: Unstable
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '12 6 * * *'
  workflow_dispatch:

jobs:
  build-unstable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branches: [master, nixpkgs-unstable]
    steps:
      - uses: ./.github/workflows/build-multiple.yml
        with: 
          branch: ${{ matrix.branches }}